### ISSUE TITLE
add "jira-assign-issue"

### ISSUE THREAD

**Issue by bradsbrown** [jolly-good-toolbelt/jiratools#4]
Add a command to assign an existing JIRA to a specified user

`jira-assign-issue {jiraID} {user}`

**Comment by bradsbrown** [comment]
Note: adding this function should involve exposing the assign logic from `jira-make-linked-issue` as a helper so that we aren't repeating code.

**Comment by ecedmondson** [comment]
I've got this one.

**Comment by ecedmondson** [comment]
I did this one so I'm going to close it.
